on:
  pull_request:
  push:
    branches: ['main']

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - run: ./format_src_check.sh
      - run: ./mill __.test
