on:
  pull_request:
  push:
    branches: ['main']

jobs:
  scalafmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - run: ./format_src_check.sh
  # license-check:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: coursier/cache-action@v6
  #     - uses: VirtusLab/scala-cli-setup@main
  #       with:
  #         jvm: temurin:21
  #     - run: scala-cli run . --main-class scripts.update_license_sc -- dry-run
